<?php

namespace CenexaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmbarazoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarazoRepository extends EntityRepository
{
}
