<?php

namespace CenexaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FichaHijoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaHijoRepository extends EntityRepository
{
}
