<?php

namespace CenexaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocumentoRepository extends EntityRepository
{
}
