<?php

namespace CenexaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadCargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadCargaRepository extends EntityRepository
{

  
}
