# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_DATAENTRY: [ROLE_SESION, ROLE_ABMPACIENTE, ROLE_ABMFICHA]
        ROLE_COORDINADOR: [ROLE_DATAENTRY, ROLE_ABMDATAENTRY]
        ROLE_ADMIN: [ROLE_MODPASSDEOTROS, ROLE_ABMUC, ROLE_EXPORTARFICHA, ROLE_ABMCOORDINADOR]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~


    firewalls:
        # disables authentication for assets and
        # the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager

            logout: true
            anonymous: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: [ROLE_ADMIN, ROLE_COORDINADOR]}
        - { path: ^/paciente, role: [ROLE_DATAENTRY]}
        - { path: ^/user, role: [ROLE_ADMIN, ROLE_COORDINADOR]}
        - { path: ^/unidadcarga, role: ROLE_ADMIN}
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }



