<?php

namespace EntityBundle\Repository;

/**
 * EmbarazoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarazoRepository extends \Doctrine\ORM\EntityRepository
{
}
