<?php

namespace EntityBundle\Repository;

/**
 * UnidadDeCargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadDeCargaRepository extends \Doctrine\ORM\EntityRepository
{
}
